[package]
name = "yy-proto"
description = "Protocol between yyeditor and its remote agent (yy-agent)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
postcard.workspace = true
miniz_oxide.workspace = true

[lints]
workspace = true
