[package]
name = "yyeditor"
description = "Lightweight text editor for Windows with huge file support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "yyeditor"
path = "src/main.rs"

[target.'cfg(windows)'.dependencies]
yy-win.workspace = true

[lints]
workspace = true
