[package]
name = "yy-core"
description = "Document model and editing core for yyeditor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
yy-buffer.workspace = true
yy-encoding.workspace = true
yy-search.workspace = true
yy-delimited.workspace = true
yy-syntax.workspace = true
memchr.workspace = true
yy-io.workspace = true
yy-jobs.workspace = true
yy-proto.workspace = true
crossbeam-channel.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[dev-dependencies]
yy-delimited.workspace = true
tempfile.workspace = true
yy-encoding.workspace = true
yy-jobs.workspace = true
proptest.workspace = true

[lints]
workspace = true
