name = "YAML"
extensions = ["yaml", "yml"]
line_comment = "#"
sync = '^\S'

[keywords]
constant = ["true", "false", "null", "yes", "no", "on", "off", "True", "False", "Null"]
[[context.main]]
match = '(?:^|\s)#.*$'
token = "comment"
[[context.main]]
match = '^---|^\.\.\.'
token = "preprocessor"
[[context.main]]
match = '^(\s*-?\s*)([^\s:#][^:#]*?)\s*:(?:\s|$)'
captures = { 2 = "property" }
[[context.main]]
begin = '"'
end = '"'
skip = '\\.'
token = "string"
[[context.main]]
begin = ''''''''
end = ''''''''
skip = ''''''''
token = "string"
[[context.main]]
match = '[&*][\w-]+'
token = "variable"
[[context.main]]
match = '!!?[\w/]+'
token = "type"
[[context.main]]
match = '-?\b[0-9]+(?:\.[0-9]+)?\b'
token = "number"
