//! `yy-encoding` の対応表を生成する（03 章 2.3）。
//!
//! usage: gen-tables <sjis-0213-2004-std.txt> > crates/yy-encoding/src/tables/jisx0213.rs
//!
//! 入力は Project X0213 が公開している Shift_JIS-2004 の対応表
//! （<https://x0213.org/codetable/sjis-0213-2004-std.txt>）。

use std::fmt::Write as _;

fn parse_cp(s: &str) -> Option<Vec<u32>> {
    let s = s.strip_prefix("U+")?;
    s.split('+')
        .map(|p| u32::from_str_radix(p, 16).ok())
        .collect()
}

fn main() {
    let path = std::env::args()
        .nth(1)
        .expect("usage: gen-tables <sjis-0213-2004-std.txt>");
    let text = std::fs::read_to_string(&path).expect("read input");
    let mut entries: Vec<(u16, u32, u32)> = Vec::new();
    for line in text.lines() {
        if line.starts_with('#') {
            continue;
        }
        let mut cols = line.split('\t');
        let (Some(code), Some(cp)) = (cols.next(), cols.next()) else {
            continue;
        };
        let Some(code) = code.strip_prefix("0x") else {
            continue;
        };
        // 1 バイトの符号は ASCII / 半角カナとして固定で扱うので 2 バイトのみ出力する
        if code.len() != 4 {
            continue;
        }
        let code = u16::from_str_radix(code, 16).expect("code");
        let Some(cps) = parse_cp(cp) else {
            continue;
        };
        let (a, b) = match cps.as_slice() {
            // ASCII と重なる文字は全角形に置き換える（1 バイト部を ASCII として扱うため）
            [0x5C] => (0xFF3C, 0),
            [0x7E] => (0xFF5E, 0),
            [a] => (*a, 0),
            [a, b] => (*a, *b),
            _ => panic!("unexpected mapping: {line}"),
        };
        entries.push((code, a, b));
    }
    entries.sort();
    let mut out = String::new();
    out.push_str(
        "// @generated by tools/gen-tables from sjis-0213-2004-std.txt (Project X0213)\n\
         // Copyright (C) 2001 earthian@tama.or.jp, All Rights Reserved.\n\
         // Copyright (C) 2001 I'O, All Rights Reserved.\n\
         // Copyright (C) 2006, 2009 Project X0213, All Rights Reserved.\n\
         // You can use, modify, distribute this table freely.\n\
         //\n\
         // (Shift_JIS-2004 の 2 バイト符号, 文字, 結合する 2 文字目または 0)\n\n",
    );
    writeln!(
        out,
        "pub(crate) static JISX0213_SJIS: [(u16, u32, u32); {}] = [",
        entries.len()
    )
    .unwrap();
    for chunk in entries.chunks(4) {
        out.push_str("   ");
        for (c, a, b) in chunk {
            write!(out, " (0x{c:04X}, 0x{a:04X}, 0x{b:X}),").unwrap();
        }
        out.push('\n');
    }
    out.push_str("];\n");
    print!("{out}");
}
