//! `yy-encoding` の対応表を生成する（03 章 2.3）。
//!
//! usage:
//!   gen-tables x0213 <sjis-0213-2004-std.txt> > crates/yy-encoding/src/tables/jisx0213.rs
//!   gen-tables ebcdic <icu-data/charset/data/ucm> > crates/yy-encoding/src/tables/ebcdic.rs
//!
//! * JIS X 0213: Project X0213 が公開している Shift_JIS-2004 の対応表
//!   （<https://x0213.org/codetable/sjis-0213-2004-std.txt>）
//! * EBCDIC: ICU の IBM CDRA 変換表（`.ucm`、<https://github.com/unicode-org/icu-data>）

use std::fmt::Write as _;
use std::path::Path;

fn parse_cp(s: &str) -> Option<Vec<u32>> {
    let s = s.strip_prefix("U+")?;
    s.split('+')
        .map(|p| u32::from_str_radix(p, 16).ok())
        .collect()
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.as_slice() {
        [cmd, path] if cmd == "x0213" => print!("{}", x0213(path)),
        [cmd, dir] if cmd == "ebcdic" => print!("{}", ebcdic(Path::new(dir))),
        _ => {
            eprintln!("usage: gen-tables x0213 <sjis-0213-2004-std.txt> | ebcdic <ucm-dir>");
            std::process::exit(2);
        }
    }
}

fn x0213(path: &str) -> String {
    let text = std::fs::read_to_string(path).expect("read input");
    let mut entries: Vec<(u16, u32, u32)> = Vec::new();
    for line in text.lines() {
        if line.starts_with('#') {
            continue;
        }
        let mut cols = line.split('\t');
        let (Some(code), Some(cp)) = (cols.next(), cols.next()) else {
            continue;
        };
        let Some(code) = code.strip_prefix("0x") else {
            continue;
        };
        // 1 バイトの符号は ASCII / 半角カナとして固定で扱うので 2 バイトのみ出力する
        if code.len() != 4 {
            continue;
        }
        let code = u16::from_str_radix(code, 16).expect("code");
        let Some(cps) = parse_cp(cp) else {
            continue;
        };
        let (a, b) = match cps.as_slice() {
            // ASCII と重なる文字は全角形に置き換える（1 バイト部を ASCII として扱うため）
            [0x5C] => (0xFF3C, 0),
            [0x7E] => (0xFF5E, 0),
            [a] => (*a, 0),
            [a, b] => (*a, *b),
            _ => panic!("unexpected mapping: {line}"),
        };
        entries.push((code, a, b));
    }
    entries.sort();
    let mut out = String::new();
    out.push_str(
        "// @generated by tools/gen-tables from sjis-0213-2004-std.txt (Project X0213)\n\
         // Copyright (C) 2001 earthian@tama.or.jp, All Rights Reserved.\n\
         // Copyright (C) 2001 I'O, All Rights Reserved.\n\
         // Copyright (C) 2006, 2009 Project X0213, All Rights Reserved.\n\
         // You can use, modify, distribute this table freely.\n\
         //\n\
         // (Shift_JIS-2004 の 2 バイト符号, 文字, 結合する 2 文字目または 0)\n\n",
    );
    writeln!(
        out,
        "pub(crate) static JISX0213_SJIS: [(u16, u32, u32); {}] = [",
        entries.len()
    )
    .unwrap();
    for chunk in entries.chunks(4) {
        out.push_str("   ");
        for (c, a, b) in chunk {
            write!(out, " (0x{c:04X}, 0x{a:04X}, 0x{b:X}),").unwrap();
        }
        out.push('\n');
    }
    out.push_str("];\n");
    out
}

/// `.ucm` の 1 行（符号, 文字, 結合する 2 文字目または 0, 精度）。
///
/// 精度は ICU の `|0`（往復）・`|1`（Unicode → 符号のみ）・`|3`（符号 → Unicode のみ）。
/// `|2`（代替文字への対応）は出力しない。
type Entry = (u16, u32, u32, u8);

/// `.ucm` を読んで 1 バイトの符号と 2 バイトの符号に分ける。
fn read_ucm(path: &Path) -> (Vec<Entry>, Vec<Entry>) {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let (mut single, mut double) = (Vec::new(), Vec::new());
    let mut in_map = false;
    for line in text.lines() {
        let line = line.trim();
        if line == "CHARMAP" {
            in_map = true;
            continue;
        }
        if line == "END CHARMAP" {
            break;
        }
        if !in_map || !line.starts_with("<U") {
            continue;
        }
        let mut cols = line.split_whitespace();
        let (Some(uni), Some(bytes), Some(prec)) = (cols.next(), cols.next(), cols.next()) else {
            panic!("bad line: {line}");
        };
        let cps: Vec<u32> = uni
            .split('>')
            .filter(|s| !s.is_empty())
            .map(|s| u32::from_str_radix(s.trim_start_matches("<U"), 16).expect("cp"))
            .collect();
        let bytes: Vec<u8> = bytes
            .split("\\x")
            .filter(|s| !s.is_empty())
            .map(|s| u8::from_str_radix(s, 16).expect("byte"))
            .collect();
        let prec: u8 = prec.trim_start_matches('|').parse().expect("precision");
        if prec == 2 {
            continue;
        }
        let (a, b) = match cps.as_slice() {
            [a] => (*a, 0),
            [a, b] => (*a, *b),
            _ => panic!("unexpected mapping: {line}"),
        };
        match bytes.as_slice() {
            [x] => single.push((*x as u16, a, b, prec)),
            [x, y] => double.push((u16::from_be_bytes([*x, *y]), a, b, prec)),
            _ => panic!("unexpected bytes: {line}"),
        }
    }
    single.sort();
    double.sort();
    (single, double)
}

fn ebcdic(dir: &Path) -> String {
    // (出力する名前, .ucm, 2 バイト部の名前)
    const SOURCES: [(&str, &str, Option<&str>); 9] = [
        ("IBM037", "ibm-37_P100-1999.ucm", None),
        ("IBM500", "ibm-500_P100-1999.ucm", None),
        ("IBM1047", "ibm-1047_P100-1995.ucm", None),
        ("IBM290", "ibm-290_P100-1995.ucm", None),
        ("IBM1027", "ibm-1027_P100-1995.ucm", None),
        ("IBM930", "ibm-930_P120-1999.ucm", Some("DBCS300")),
        ("IBM939", "ibm-939_P120-1999.ucm", Some("DBCS300")),
        ("IBM1390", "ibm-1390_P110-2003.ucm", Some("DBCS16684")),
        ("IBM1399", "ibm-1399_P110-2003.ucm", Some("DBCS16684")),
    ];
    let mut out = String::new();
    out.push_str(
        "// @generated by tools/gen-tables from the IBM CDRA conversion tables in ICU\n\
         // (https://github.com/unicode-org/icu-data, charset/data/ucm).\n\
         // Copyright (C) 1995-2007, International Business Machines Corporation and others.\n\
         // Copyright © 2016-2024 Unicode, Inc. Distributed under the Unicode License V3\n\
         // (https://www.unicode.org/license.txt).\n\
         //\n\
         // (符号, 文字, 結合する 2 文字目または 0, 精度 0=往復 1=Unicode→符号のみ 3=符号→Unicodeのみ)\n",
    );
    let mut dbcs: Vec<(&str, Vec<Entry>)> = Vec::new();
    for (name, file, dname) in SOURCES {
        let (single, double) = read_ucm(&dir.join(file));
        write_table(&mut out, name, "u8", &single);
        match dname {
            None => assert!(double.is_empty(), "{file}: unexpected DBCS"),
            Some(d) => match dbcs.iter().find(|(n, _)| *n == d) {
                Some((_, prev)) => assert!(*prev == double, "{file}: DBCS differs from {d}"),
                None => dbcs.push((d, double)),
            },
        }
    }
    for (name, entries) in &dbcs {
        write_table(&mut out, name, "u16", entries);
    }
    out
}

fn write_table(out: &mut String, name: &str, code: &str, entries: &[Entry]) {
    writeln!(
        out,
        "\npub(crate) static {name}: [({code}, u32, u32, u8); {}] = [",
        entries.len()
    )
    .unwrap();
    let width = if code == "u8" { 2 } else { 4 };
    for chunk in entries.chunks(4) {
        out.push_str("   ");
        for (c, a, b, p) in chunk {
            write!(out, " (0x{c:0width$X}, 0x{a:04X}, 0x{b:X}, {p}),").unwrap();
        }
        out.push('\n');
    }
    out.push_str("];\n");
}
